adding ubuntu 24.04
hivesolutions/docker pull request #20
Opened 2024-04-30 11:16 UTC by hugo-gomes

2024-04-30 15:04 UTC, hugo-gomes commented on ubuntu/Dockerfile
> -    apt-get install -y -q --no-install-recommends sudo bash wget git openssl unzip ca-certificates dirmngr apt-transport-https python2 python3 python3-distutils &&\
@joamag python2 was removed due to its incompatibility with libssl3 on Ubuntu Noble

2024-04-30 15:05 UTC, hugo-gomes commented on ubuntu/Dockerfile.rolling
> -    apt-get install -y -q --no-install-recommends sudo bash wget git openssl unzip ca-certificates dirmngr apt-transport-https python3 python3-distutils &&\
@joamag distutils is deprecated and was removed on python 3.12

2024-05-01 07:29 UTC, joamag commented
@hugo-gomes  I believe the build seems to be failing

2024-05-01 07:30 UTC, joamag commented
@hugo-gomes please add a simple description on the changes and rationale

2024-05-02 19:13 UTC, hugo-gomes commented
@joamag description addded.

<img width="550" alt="Screenshot 2024-05-02 at 20 12 15" src="https://github.com/hivesolutions/docker/assets/20085/f04630fc-78bb-4f38-b8d2-c91a6823d698">

`hivesolutions/ubuntu_dev:noble` is failing because `hivesolutions/ubuntu:noble` is not yet available. both are being added with this PR.

2024-05-02 21:37 UTC, joamag requested changes

2024-05-02 21:37 UTC, joamag commented on ubuntu/Dockerfile
>  ARG DEBIAN_FRONTEND=noninteractive
let's instead make use of the latest ubuntu version that allowed python2 (change FROM instead) otherwise we will have many problems downstream

2024-05-03 20:31 UTC, joamag approved these changes

2024-05-03 20:31 UTC, merged